FROM circleci/node:8

RUN sudo apt-get install awscli
RUN sudo apt-get install python-setuptools
RUN sudo easy_install pip
RUN sudo apt-get install python-dev        
RUN sudo pip install --upgrade awscli