FROM circleci/php:5.6-apache-node-browsers

RUN apt-get install awscli \
    apt-get install python-setuptools \
    easy_install pip \
    apt-get install python-dev \  
    pip install --upgrade awscli